# Generated by Django 4.0.2 on 2022-06-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liking', to=settings.AUTH_USER_MODEL)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='network.post')),
            ],
        ),
    ]
